services:
  - type: web
    name: yum-recipes-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    branch: ganymed
    envVars:
      - key: NODE_ENV
        value: prod
      - key: PORT
        value: 3000
      - key: MONGO_URI
        fromDatabase:
          name: yum-recipes-mongo
          property: connectionString
